apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: website-image:$(date +%s)
          ports:
            - containerPort: 8080
            